### ISSUE TITLE
[BUG] lack of color integrity

### ISSUE THREAD

**Issue by mnkhprre** [tefkah/zotero-night#75]
**Describe the bug**

there are a couple of theme bugs and hard to read dark font on the dark theme 

**Screenshots**
If applicable, add screenshots to help explain your pr
<img width="1440" alt="Screen Shot 2022-09-30 at 11 37 00" src="https://user-images.githubusercontent.com/54448793/193229423-19b655b9-eb76-44db-b68b-41520c668776.png">
<img width="1440" alt="Screen Shot 2022-09-30 at 11 47 33" src="https://user-images.githubusercontent.com/54448793/193231369-49631f45-874e-4174-a6d6-74917a29df38.png">
<img width="199" alt="Screen Shot 2022-09-30 at 11 50 08" src="https://user-images.githubusercontent.com/54448793/193231850-8b1972b0-cf0b-46d9-af08-969ac13667a3.png">

oblem.

**OS (macOS XX.xx [specify Intel or Silicon], Windows, Linux [specify distro/package type]:**
intel-based Macbook pro 13" 2020 model. I am using macOS Monterey 12.6
**Zotero Night version (please check that you are on the latest version)**
I am using Zotero 6.0.14
**Additional context**

**Comment by tefkah** [comment]
Thank you!

**Comment by mnkhprre** [comment]
> Thank you!

you are welcome. if you make it efficient to use for academic purposes. I am thinking to use it on my MA thesis notes

**Comment by AlexMeier99** [comment]
Hi @tefkah @mnkhprre 

after quite a while of seeing this project growing I tune in again to share some CSS to fix the bugs above:

```css
/* toggle buttons top right in reader view */
[theme="dark"] #zotero-tb-toggle-item-pane, [theme="dark"] #zotero-tb-toggle-notes-pane{
  background: var(--nord1) !important;
}
[theme="dark"] #zotero-tb-toggle-item-pane span, [theme="dark"] #zotero-tb-toggle-notes-pane span {
  display: none;
}
[theme="dark"] #zotero-tb-split {
  background: var(--nord0) !important;
}

/* ------------------------------- */

/* 'deck' context notes pane */
[theme="dark"] #zotero-context-toolbar-extension,
[theme="dark"] .zotero-context-notes-list,
[theme="dark"] .notes-list-container {
  background: var(--nord0) !important;
  color: var(--nord5) !important;
}

/* search bar at the top of context notes pane */
[theme="dark"] .zotero-context-notes-list textbox[type="search"]{
  filter: var(--dark-filter);
}

/* '+' button */
[theme="dark"] .header-row button {
  background-color: var(--nord2) !important;
  color: var(--nord5) !important;
}

/* boxes/cards for notes 'rows' in context notes pane */
[theme="dark"] .note-row,
[theme="dark"] .more-row{
  background-color: var(--nord2) !important;
  color: var(--nord5) !important;
}

/* ------------------------------- */

/* related items tab pane -> 'add' button */
[theme="dark"] .zotero-editpane-related #addButton {
  -moz-appearance: none !important;
  background-color: var(--nord2) !important;
  color: var(--nord5) !important;
}

/* --------------------------------- */

/* 'add' notes button in library view*/
[theme="dark"] #zotero-editpane-notes-add {
  -moz-appearance: none !important;
  background-color: var(--nord2) !important;
  color: var(--nord5) !important;
}

/* --------------------------------- */

/* new tag input in 'tags' tab pane */
[theme="dark"] .tag .editable.editing {
  filter: var(--dark-filter);
}

/* --------------------------------- */

/* dropdown icon button of 'author'/publisher data entry field in first context tab */
[theme="dark"] .creator-type-label image {
  filter: var(--dark-filter);
}
```

[📁 userchrome.css](https://github.com/tefkah/zotero-night/files/9715292/userchrome.css.txt)

I didn't expected this much interest when I shared my workflow for opening the zotero/firefox dev tools back in april. I'm very grateful that @tefkah developed this plugin. Please keep up the great work!
